#pragma once
#include <Arduino.h>

#define PUMP_PIN 23
#define PH_CALIBRATION_A -4.2537
#define PH_CALIBRATION_B 17.4943
#define PH_SENSOR_PIN 32
#define TDS_SENSOR_PIN 33
#define LEVEL0_SENSOR_PIN 21
#define LEVEL1_SENSOR_PIN 25
#define LEVEL2_SENSOR_PIN 35
#define TEMP_SENSOR_PIN 27
#define VREF 3.3
#define EC_MEASURE_COUNT 30
#define PH_MEASURE_COUNT 20
